# Generated by Django 6.0.5 on 2026-05-14 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_name_alter_client_phone'),
        ('sales', '0002_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'sales_invoice_counter',
            },
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada')], db_index=True, default='pagada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_active', 'status', '-date'], name='idx_sale_active_status_date'),
        ),
    ]
