# Generated by Django 6.0.5 on 2026-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoicecounter_alter_saleitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto recibido'),
        ),
        migrations.AddField(
            model_name='sale',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cambio'),
        ),
    ]
