# Generated by Django 6.0.5 on 2026-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_amount_received_sale_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('pendiente', 'Pendiente')], default='efectivo', max_length=50, verbose_name='Método de pago'),
        ),
    ]
