# Generated by Django 6.0.5 on 2026-05-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_name_alter_client_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientInvoice',
        ),
    ]
