# Generated by Django 6.0.5 on 2026-05-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_delete_clientinvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='rfc',
            new_name='cc',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
