# Generated by Django 6.0.5 on 2026-05-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
