# Generated by Django 6.0.5 on 2026-05-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_name_alter_supplier_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='rfc',
            new_name='nit',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
