# Generated by Django 6.0.5 on 2026-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_supplier_rfc_supplier_nit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'suppliers_invoice_counter',
            },
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nit',
            field=models.CharField(blank=True, max_length=13, verbose_name='NIT'),
        ),
    ]
